services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"  # Internal container communication
      - "9094:9094"  # External host communication
    environment:
#      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094'
#      KAFKA_CFG_CONTROLLER: 'CONTROLLER'
#      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '0@kafka:9093'
#      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
#      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
#      KAFKA_CFG_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:9094'
#      KAFKA_CFG_NODE_ID: '0'
#      KAFKA_CFG_PROCESS_ROLES: 'controller,broker'



# ;=0@kafka:9093;KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT;KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094;KAFKA_CFG_NODE_ID=0;KAFKA_CFG_PROCESS_ROLES=controller,broker

      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: 'controller,broker'
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '0@kafka:9093'
      KAFKA_CFG_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:9094'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP:
      KAFKA_CFG_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094'
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - patient-management


  analytics-service:
    build: ./analytics-service
    container_name: analytics-service
    environment:
      SPRING_KAFKA_BOOTSTRAP_SEVERS: 127.0.0.1:9092
    ports:
      - "4002:4002"
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - patient-management


  patient-service:
    build: ./patient-service
    container_name: patient-service
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    networks:
      - patient-management


networks:
  patient-management:
    driver: bridge
#      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9094"
#      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094"
#      KAFKA_LISTENER_NAME: "PLAINTEXT"
#      KAFKA_LISTENER_DEFAULT: "PLAINTEXT"


